title: Intro2ML
email: m.williams.4@research.gla.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  Intro2ML aims to introduce you to some of the basic concepts of machine learning 
  in an interactive manner.
baseurl: "/intro2ml" # the subpath of your site, e.g. /blog
url: "https://mj-will.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: michael_j_will
    github:  mj-will

collections:
  topics:
    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

